### PR TITLE
Fix no_std

### PR DESCRIPTION
**Pull request by koushiro**
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

@ia0  Please release a patch version after merging this PR

### CODE REVIEW

**Comment by ia0** [comment]
Hi @koushiro,

Thanks for the PR! However, I think this is not needed. Did you try to update your `.cargo/config.toml` as described [here](https://crates.io/crates/data-encoding-macro)? Also, note that this should not be needed anymore with recent rustc versions, although I did not have time to try yet.

**Comment by koushiro** [comment]
see https://github.com/multiformats/rust-multibase/pull/39/checks?check_run_id=1722464743 for details

**Comment by koushiro** [comment]
you could run the command `cargo build --target thumbv6m-none-eabi` under the path `data-encoding/lib/macro`

**Comment by ia0** [comment]
Thanks for the link, I've added a comment there. I'm closing the issue here.

See also https://github.com/ia0/data-encoding/pull/35 for previous discussions regarding multiformats/rust-multibase.

**Pull request closed without merging**
