### PR TITLE
Downgrade MSRV to 1.48

### PR DESCRIPTION
**Pull request by sdroege**
This is the version currently available in Debian oldstable and should be a
    reasonable choice.
    
    Also check in the CI that everything still compiles with that version
    and fixed Cargo.lock files that use older dependency versions than what
    cargo would select by itself.

### CODE REVIEW

**Comment by sdroege** [comment]
I'll try fixing the remaining CI issues tomorrow

**Comment by ia0** [comment]
> I'll try fixing the remaining CI issues tomorrow

I'm taking a look at it now in #87 because it's some annoying xtask shenanigans and possibly dealing with windows testing in github.

**Comment by ia0** [comment]
Ok, apparently powershell has aliases for `cp` and `mv`, so it worked fine. If it's fine with you I'll merge #87 which is your commit and an xtask commit on top (also dealing with lints and updating the changelog).

**Comment by sdroege** [comment]
Let's merge yours then, that's already ready and doesn't need another CI run :)
You could've also pushed that commit directly into this PR btw, but doesn't really matter.

**Comment by sdroege** [comment]
Also thanks for fixing up the CI :)

**Comment by ia0** [comment]
> You could've also pushed that commit directly into this PR btw, but doesn't really matter.

I wasn't sure I had permission to push to your branch. But it doesn't change anything AFAIU (squashed PRs with multiple authors are authored by the merger and co-authored by the rest).

> Also thanks for fixing up the CI :)

No worries, that was on me anyway. And thanks again for bringing this issue to my attention! And I'm actually surprised you discovered it because the MSRV bump was not even released, which means you had to take a look at the repo.

**Pull request closed without merging**
